### ISSUE TITLE
Building native libraries against packaged Openssl

### ISSUE THREAD

**Issue by TheMidgardWatcher** [redhat-developer/s2i-dotnetcore#152]
Hi there.

I have a question - how can I install or add to template openssl 1.0.x library which I need to run my aspnet core 2.0 application on "dotnet-20-rhel7:2.0" image based container?

**Comment by aslicerh** [comment]
Hi @TheMidgardWatcher!

Can you clarify a bit about your question? The dotnet-20-rhel7 should already have the openssl 1.0 devel library in it, so are you seeing an issue where you need a different version of the openssl lib or are you seeing a failure of some kind while trying to use it?

**Comment by TheMidgardWatcher** [comment]
Hi @aslicerh 

Could you please have a look into my issue in repo of that lib I'm trying to run:
https://github.com/confluentinc/confluent-kafka-dotnet/issues/389#issuecomment-350010483

**Comment by aslicerh** [comment]
@TheMidgardWatcher 
Ok, so I have a feeling the issue is that what you compiled on you win machine is expecting a different version of openssl. I cloned a copy of the other project you're working with and ran the `./configure` on the container and it was able to find libcrypto and libssl just fine.

Can you try building librdkafka in the container instead of windows?

Or can you build it on your win machine with openssl 1.0.2k instead of 1.0.0?

**Comment by TheMidgardWatcher** [comment]
@aslicerh 
In my case - I didn't compiled anything on my local win workstation. I've just published project with rhel as a target platform, and then I've put 'so' binaries into my project folder from published output folder. Then inside code I'm trying to load needed library manually from app's root directory. And I got this message:

`InvalidOperationException: Failed to load librdkafka at location '/opt/app-root/app/librdkafka.so'. dlerror: 'libcrypto.so.1.0.0: cannot open shared object file: No such file or directory'.`

As I'm not experienced user in docker, openshift and all other stuff (All environment is managed by other team) this task to build something inside container (actually for me it's OpenShift's pod) is too tricky for me...

**Comment by jerboaa** [comment]
@TheMidgardWatcher [Your comment](https://github.com/confluentinc/confluent-kafka-dotnet/issues/389#issuecomment-349607524) on https://github.com/confluentinc/confluent-kafka-dotnet/issues/389 suggests you did compile the native library on Windows so as to get the `so` libraries.  Hence, @aslicerh response that this won't work. I.e. compiling the native bits on one platform and then copying into another.

Here is my understanding of the issue:

@TheMidgardWatcher would like to use [Kafka .NET client](https://github.com/confluentinc/confluent-kafka-dotnet/) in an ASP.NET app. That client depends on [a native library](https://github.com/edenhill/librdkafka) which needs to be properly linked to the RHEL/CentOS SCL OpenSSL. In order to get such compatible native library, it must be built on a compatible platform to the runtime container (i.e. CentOS 7 or RHEL 7).

The issue at hand is that the Kafka .NET client library is currently not compatible with CentOS/RHEL. It's really an issue of that library, not our .NET containers. That's https://github.com/confluentinc/confluent-kafka-dotnet/issues/389

What we could do, though, is produce some best practices how to build native libraries using our containers. @aslicerh @omajid @tmds Thoughts?

**Comment by tmds** [comment]
> InvalidOperationException: Failed to load librdkafka at location '/opt/app-root/app/librdkafka.so'. dlerror: 'libcrypto.so.1.0.0: cannot open shared object file: No such file or directory'.

@TheMidgardWatcher if your `librdkafka` would look for `libcrypto.so.10` it would find it. You could try to compile it as such. Or you can can add a symlink and update LD_LIBRARY_PATH in the container.
e.g. add a `.s2i/bin/run` to your repo (untested):
```
#!/bin/bash

# create library symlinks
LIBDIR=$HOME/mylibs
mkdir $LIBDIR
ln -s /lib64/libcrypto.so.10 $LIBDIR/libcrypto.so.1.0.0
export LD_LIBRARY_PATH=$LIBDIR:$LD_LIBRARY_PATH

# call base run script
exec $STI_SCRIPTS_PATH/run
```

> What we could do, though, is produce some best practices how to build native libraries using our containers. @aslicerh @omajid @tmds Thoughts?

I'm not sure how often this will happen. I think we can wait until we get some more cases and then derive some guidelines based on how we tackled them.

**Comment by TheMidgardWatcher** [comment]
Hi @tmds,

Thanks for your suggestion, it works great!
I've done as you mentioned, also I've add one more line:
`ln -s /lib64/libssl.so.10 $LIBDIR/libssl.so.1.0.0`

And it works too. But that's not the end. 
After all this manipulations I've got this message:
```
An unhandled exception occurred while processing the request.

InvalidOperationException: Failed to load librdkafka at location '/opt/app-root/app/librdkafka.so'. dlerror: '/lib64/libcrypto.so.10: version `OPENSSL_1.0.0' not found (required by /opt/app-root/app/librdkafka.so)'.
Confluent.Kafka.Impl.LibRdKafka.Initialize(string userSpecifiedPath)
```
As I understand, even so I need to build native library inside of container against correct version of OpenSSL or to install proper version into container.
@tmds am I right?

PS: I very appreciate your help!

**Comment by tmds** [comment]
> As I understand, even so I need to build native library inside of container against correct version of OpenSSL or to install proper version into container.

Yes, librdkafka can't work with the newer version of openssl that is in the image. You can build on RHEL7, it doesn't matter if it is in a container or not.
When you've build librdkafka on RHEL7 you should no longer need to manually create the symlinks.

**Comment by TheMidgardWatcher** [comment]
Thanks guys for all the answers! I think further steps I'll take by myself or/and with librdkafka team.

**Comment by tmds** [comment]
Nothing to be done for this issue in s2i-dotnetcore.
