### ISSUE TITLE
[Enhancement] Allow custom CA's to be provided via a config map

### ISSUE THREAD

**Issue by sferich888** [redhat-developer/s2i-dotnetcore#162]
Custom CA's should be provided via a configuration map so that the .net application can use them at build time or during the application's runtime, as the CA's would be built into the image. 

If I am not mistaken, we could simply put `update-ca-trust extract` at  this [line](https://github.com/redhat-developer/s2i-dotnetcore/blob/master/2.0/build/s2i/bin/assemble#L12) in the assemble script or at this [line](https://github.com/redhat-developer/s2i-dotnetcore/blob/master/2.0/build/s2i/bin/run#L3) as part of the run script (not the ca's could not be used a build time then) and any config map that provides custom CA's to _/etc/pki/ca-trust/source/anchors/_ would be available to the container at startup. 

Following: https://access.redhat.com/solutions/1519813

**Comment by tmds** [comment]
> Following: https://access.redhat.com/solutions/1519813

Did you give this a try? The solution has `# ` so I think it may need root privileges, which we don't have when running in OpenShift.

**Comment by sferich888** [comment]
You will at build time. In addition to that, if I am not mistaken the commands were runnings source is from or mirrored at https://github.com/special/ca-certificates/blob/master/update-ca-trust so even if we did not want to run these commands we could run other commands (and have user owned CA files). 

That said, at startup we should have a way to do this process.

**Comment by bparees** [comment]
> You will at build time.

if by build time you mean "Assemble script execution" then no, you still don't.  The assemble script runs as the default user for the image, which could be root, but shouldn't be because openshift will, by default, refuse to perform s2i builds if the image uses root as the default user.

The normal solution to this, which may or may not be feasible for this particular action, is to setup the permissions in the image(ie when you originally built the s2i-builder image) such that the assemble user can perform the actions (ie allowing the default image user to write to files that might normally only be writable by root).

**Comment by tmds** [comment]
With 2.1 it is possible to specify a certificate bundle using the SSL_CERT_FILE envvar.

There is an RFE to backport this to 2.0: https://bugzilla.redhat.com/show_bug.cgi?id=1552812

**Comment by tmds** [comment]
@sferich888 I'm closing this as we won't fix this in s2i. If you have interest in the 2.0 backport please add a comment and follow-up on https://bugzilla.redhat.com/show_bug.cgi?id=1552812.
