### ISSUE TITLE
Move CI to faster machine

### ISSUE THREAD

**Issue by tmds** [redhat-developer/s2i-dotnetcore#170]
CI builds on PR takes 2h20min. I hope this reduces significantly when we move to faster CI machines.

CC @RheaAyase

**Comment by RheaAyase** [comment]
assign-to

**Comment by tmds** [comment]
I don't assign issues to people. When creating issues I CC folks who may be interested/should be informed. If you are working on an issue you can self-assign it. Otherwise you can leave it open and someone else can pick it up.

**Comment by RheaAyase** [comment]
I can't, that's'what I was asking on irc as well. I don't have permission to.

**Comment by tmds** [comment]
Ah I didn't get that. Should work now.

**Comment by tmds** [comment]
Nothing happens for this PR: https://github.com/redhat-developer/s2i-dotnetcore/pull/173

**Comment by RheaAyase** [comment]
So it seems that the job is running fine, but the build fails. This is the master branch test, not the PR test. The PR is failing due to github credentials, aaaand I seem to be too much of a noob to figure out why or how to set it up so it actually works... Anyone with a bit more experience in the whole jenkins-github thing to take a look?

**Comment by tmds** [comment]
Can you try to add the github server under 'Manage Jenkins' > 'Configure System' > 'Github'?

**Comment by RheaAyase** [comment]
Well, that has empty credentials as well, ignoring all the ones correctly configured, and hitting the add button does create yet another entry in the credentials, but it is not available in the very list you click add for. The list is still empty.

**Comment by tmds** [comment]
Try using Kind 'secret file'/'secret text' when creating the credentials. For more info: https://stackoverflow.com/questions/36500729/jenkins-github-plugin-cant-choose-my-credentials

**Comment by RheaAyase** [comment]
You see, that's the joke... I created this job as an exact copy of the one on tonnerre, which was using username and password. The github account did not have a token on it at all... We'll see if this helps...

**Comment by RheaAyase** [comment]
Any ideas who can fix it? It's obviously still not working, and all the options were exhausted...

**Comment by aslicerh** [comment]
Ok, I think it is fixed now. Not sure if it is faster, but part of that is how the tests have grown from before as well.

**Comment by RheaAyase** [comment]
We would still need to review the jobs that are there, kick out the ones we don't need, and modify cron on the ones that are supposed to build regularly - we should build it past midnight UTC until 8am UTC, so that way the machine is free-ish for more nimble PR work, QE/release stuff, simply human triggered stuff hehe

**Comment by tmds** [comment]
We should look at splitting the CI into a number of jobs. Now it takes a really long time (due to all the versions) and if there is a hickup, we need to start all over again.

**Comment by tmds** [comment]
Closing since CI moved to a different machine, and fast is relative :smile:
