### ISSUE TITLE
Update to 3.1.2

### ISSUE THREAD

**Issue by Hoffs** [redhat-developer/s2i-dotnetcore#316]
3.1.2 has been released which contains quite an important cpu clipping fix especially relevant for cloud environments. S2I should be updated with these too. Or are these being worked on already?

https://devblogs.microsoft.com/dotnet/net-core-february-2020/
https://github.com/dotnet/runtime/issues/622

**Comment by tmds** [comment]
This release has hit some internal delay, and because it is not a security release, the delay are considered acceptable.
I agree that this fix is important for .NET Core running in container environments.
If you have a Red Hat subscription, consider filing a ticket.
I will raise some awareness at Red Hat.

**Comment by tmds** [comment]
@Hoffs this fix is now available in rhel7 based containers, and will be available in rhel8 based containers tomorrow. Sorry for the delay!
