### ISSUE TITLE
[.NET 8] (maybe) add .NET version environment variables

### ISSUE THREAD

**Issue by tmds** [redhat-developer/s2i-dotnetcore#459]
Microsoft .NET images include environment variables for the .NET and ASP.NET Core version.

It would be nice if we could do the same, if we can make that work with our container build system.

```
DOTNET_VERSION=8.0.0-preview.6.23329.7
ASPNET_VERSION=8.0.0-preview.6.23329.11
```

cc @aslicerh @omajid

**Comment by tmds** [comment]
And if we're adding these, we can also consider to remove:
```
DOTNET_CORE_VERSION=7.0
DOTNET_FRAMEWORK=net7.0
```

**Comment by tmds** [comment]
Currently we need to update the tests scripts with the right version in order for them to pass.
This would require updating the version in some other place.

@aslicerh @omajid is this feasible?

**Comment by aslicerh** [comment]
If we made it a feature (something declared in container environment) then we could use it to test instead of declaring the expected version in the tests. I.E. Does the installed .NET version match what has been set in the container ENV. This would mean the same level of changing things, it would just be different where things get changed.
