### ISSUE TITLE
Remove support for s2i builds with pre-built artifacts from runtime image [9.0]

### ISSUE THREAD

**Issue by tmds** [redhat-developer/s2i-dotnetcore#492]
Since long (.NET Core 2.1) our runtime images have supported s2i with taking pre-built artifacts as their input.

The goal of this was to facilitate building .NET application images that used the runtime image as a base image rather than the SDK image.

With .NET 8, the .NET SDK is now capable of building .NET application images directly on top of runtime images.

This issue is for removing the s2i feature from the runtime image and have users adopt an SDK-based pipeline instead.

Note that this will have no impact on users using s2i with the SDK image.

cc @omajid @aslicerh

**Comment by omajid** [comment]
I have mixed feelings about this. On one hand, I agree that re-implementing/testing/maintaining something that the SDK already does for us is not good investment. On the other hand, this is a recent/new feature in the SDK and if it has bugs or doesn't work correctly, having an known-to-work alternative/workaround might be nice to have.

**Comment by tmds** [comment]
> having an known-to-work alternative/workaround might be nice to have

The SDK image also supports taking in the pre-built artifacts. So, as a stopgap (while users adopt an alternative pipeline) they can use the 9.0 SDK image. Their application images will be based on that SDK image, so: the size will increase, but still be functional.

I don't think there effectively are many users of this feature because: it requires crafting a specific pipeline, and it is s2i specific (roughly translates to: OpenShift). On OpenShift, probably you prefer to use s2i with the SDK image, because the gains of the specific pipeline are fairly low.

> this is a recent/new feature in the SDK and if it has bugs

We should ensure the SDK works with our images. S2I with the runtime image isn't an alternative/workaround for that.

I would prefer to steer users towards recommended options. If we get feedback from users that they really want this feature, we can add it back.

**Comment by dnperfors** [comment]
Hi @tmds,

I just found out that I am the user that hits a wall with this change. And although this is large because of how our infrastructure is set up, I realy want to pick your brain on how I can change my builds with minimal effort towards the recommended way of working.

Our typical workflow with .NET applications:

1. We build the application in a pipeline outside openshift
2. During the build we test the application and run some analysis against it
3. We then use the openshift build templates to push the build artifacts to the runtime image (unfortunattely on two different openshift environments). For this s2i is used.

The reason for this way of working is that we only want to build the application once, and not 3 times, and we don't want our builds to happen on OpenShift since that is less readable when something fails (for example some tests that fail). Besides that, we didn't really get building using the SDK image and passing the output to the runtime working.
Could you give me some pointers on how to solve this?
