### ISSUE TITLE
Add DOTNET_RESTORE_SOURCES environment variable

### ISSUE THREAD

**Issue by jnordell** [redhat-developer/s2i-dotnetcore#57]
As a OpenShift cluster administrator I want to be able to define a build defaults variable for NuGet. Similar to MAVEN_MIRROR_URL, NPM_MIRROR or PIP_INDEX_URL

**Comment by tmds** [comment]
\cc @tanaka-takayoshi

**Comment by tmds** [comment]
@jnordell @tanaka-takayoshi for your use-case 1 source is enough, right?

When allowing multiple sources, depending on the relationship between the sources, the --ignore-failed-sources flag should be added.

Since the use case is caching on OpenShift, I propose we only support 1 source set as DOTNET_RESTORE_SOURCE.

**Comment by jnordell** [comment]
@tmds @tanaka-takayoshi I would think that 1 default source is ok and if the developers need anything else they would have to add a NuGet.config pointing to the extra source(s)

**Comment by tlbdk** [comment]
@jnordell I had a bit of time to create a bash script to generate a NuGet.config in the build root if nothing exists already, also I renamed the variable to DOTNET_NUGET_SOURCES.

It handles multiple source this way: 
DOTNET_NUGET_SOURCES="http://source1 http://source2" 

Pull request:
https://github.com/redhat-developer/s2i-dotnetcore/pull/58

**Comment by tmds** [comment]
@tlbdk sources can be specified to the `dotnet restore` command using `--source `, there is no need to manually assemble a NuGet.config file.

**Comment by tmds** [comment]
@tlbdk your use-case is the one already mentioned here "caching in OpenShift"?

**Comment by tlbdk** [comment]
How does that work with overwrites done in the project, fx. if they project is importing it's own sources?

**Comment by tmds** [comment]
> How does that work with overwrites done in the project, fx. if they project is importing it's own sources?

From https://docs.microsoft.com/en-us/dotnet/articles/core/preview3/tools/dotnet-restore:

> Specifies a NuGet package source to use during the restore operation. This overrides all of the sources specified in the NuGet.config file(s). Multiple sources can be provided by specifying this option multiple times.

**Comment by tlbdk** [comment]
So any specified in the project folder would be ignored i guess? Generating NuGet.config makes it possible to append to the sources on a per project basis.

**Comment by tlbdk** [comment]
But I could live with building the "dotnet restore" --source list instead, would that have a higher chance of getting merged?

**Comment by tlbdk** [comment]
And just to outline my use case, we are developing a project using the public nuget.org sources on internet connected laptops, but building and deploying on the corp network where we have to use local mirrors. So instead of keeping the mirror list in the repo i would be nice if we could keep it on corp network in the OpenShift configuration.

**Comment by tmds** [comment]
Thanks for clarifying the use-case. The corporate server acts as a cache for NuGet? Do you also store your own packages on it? How many source urls do you need to restore on your corporate network?

**Comment by tlbdk** [comment]
As far as I know it's a sync and not a cache. 
Our packages are store depending on where they where built, so fx. TFS has one location and Gitlap might have another one.
Right now I have to include 3 sources to restore my project.

**Comment by tmds** [comment]
> As far as I know it's a sync and not a cache.
Our packages are store depending on where they where built, so fx. TFS has one location and Gitlap might have another one.
Right now I have to include 3 sources to restore my project.

Multiple sources will be a typical thing. So DOTNET_RESTORE_SOURCE is of the table, we at least need DOTNET_RESTORE_SOURCES.

An alternative for DOTNET_RESTORE_SOURCES would be to provide a DOTNET_RESTORE_CONFIGFILE variable which the user can set to another NuGet.config file in his repository. The benefit of this is that he can control everything. The drawback it is no longer only possible to configure in OpenShift only since he must add a file to his repository.

@tlbdk If DOTNET_RESTORE_SOURCES meets your use-case let's add that.
My preference is to use the --source flag of dotnet restore. I would like to stay away from xml parsing and generating in bash as long as we can. When we add the feature it needs to include a test. We can setup a feed at myget for this.

**Comment by tlbdk** [comment]
I updated the pull request so it now uses the --source flags

**Comment by tmds** [comment]
@tlbdk great, I will do a review. We need to add a test too. I want to use the myget service with a dummy package that isn't on NuGet.

**Comment by tlbdk** [comment]
I guess we can close this one, since the merge of #58

**Comment by tmds** [comment]
Implemented in #58

**Comment by jerboaa** [comment]
Note, if the PR comment (the commit message) had contained "closes #58" the issue would have auto-closed on PR merge time.
