### ISSUE TITLE
Split build documentation

### ISSUE THREAD

**Issue by tmds** [redhat-developer/s2i-dotnetcore#93]
- We are missing documentation on how to configure OpenShift to do a split build.
- For 2.0 we have a 2 README files (one under build, and one under runtime). Can we have a single README?

@aslicerh can you take care of this?

**Comment by jerboaa** [comment]
I think it would be easiest to provide a template which uses the advanced split-image approach. That is, add a template which:

1. Uses the 2.0 builder image `dotnet/dotnet-20-rhel7` in order to build https://github.com/redhat-developer/s2i-dotnetcore-ex into an image
2. Massages the result to run via `dotnet/dotnet-20-runtime-rhel7`

**Comment by aslicerh** [comment]
The split image documentation and template was taken care of in PR #102.

Do we actually want to combine the 2.0 docs into a single README?

**Comment by tmds** [comment]
> Do we actually want to combine the 2.0 docs into a single README?

It's no longer an option. The READMEs should stay where they are now. The image streams and docs contain references.
